services:
  ooklaserver:
    image: ookla/ooklaserver:latest
    container_name: ooklaserver
    restart: unless-stopped
    volumes:
      - ${PWD}:/opt/ooklaserver/data
      - ${PWD}:/opt/ooklaserver/certs
    environment:
      # All environment variables are optional
      # OoklaServer user and group
      OOKLASERVER_USER: ooklaserver
      OOKLASERVER_GROUP: ooklaserver

      # Properties file configuration
      # Default is Ookla provided default
      PROPERTIES_FILE: OoklaServer.properties
    ports:
      - "8080:8080"
      - "5060:5060"
    network_mode: host

volumes:
  ooklaserver_config:
  ooklaserver_certs:
